In [29]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
WITH b AS(
SELECT memid, facid,
	CASE WHEN starttime LIKE '2012-09%'
			THEN 'September'
		 WHEN starttime LIKE '2012-08%'
			THEN 'August'
		 ELSE 'July' END AS month
FROM Bookings)
SELECT f.name AS facility_name, b.month, COUNT(*) AS month_usage
FROM Members AS m
INNER JOIN b ON m.memid=b.memid
INNER JOIN Facilities AS f ON b.facid=f.facid
WHERE m.memid != 0
GROUP BY f.name, b.month
ORDER BY f.name, b.month

        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', 'August', 132)
('Badminton Court', 'July', 51)
('Badminton Court', 'September', 161)
('Massage Room 1', 'August', 153)
('Massage Room 1', 'July', 77)
('Massage Room 1', 'September', 191)
('Massage Room 2', 'August', 9)
('Massage Room 2', 'July', 4)
('Massage Room 2', 'September', 14)
('Pool Table', 'August', 272)
('Pool Table', 'July', 103)
('Pool Table', 'September', 408)
('Snooker Table', 'August', 154)
('Snooker Table', 'July', 68)
('Snooker Table', 'September', 199)
('Squash Court', 'August', 85)
('Squash Court', 'July', 23)
('Squash Court', 'September', 87)
('Table Tennis', 'August', 143)
('Table Tennis', 'July', 48)
('Table Tennis', 'September', 194)
('Tennis Court 1', 'August', 111)
('Tennis Court 1', 'July', 65)
('Tennis Court 1', 'September', 132)
('Tennis Court 2', 'August', 109)
('Tennis Court 2', 'July', 41)
('Tennis Court 2', 'September', 126)